### PR TITLE
Set default image sizes so they work without js

### PR DESCRIPTION
**Pull request by atondwal**
(I haven't tested this yet, since I can't get the blog to build on my machine...)

### CODE REVIEW

**Comment by ranjitjhala** [comment]
Yikes, can you build? Don't want to merge something that no one has tested...

**Comment by atondwal** [comment]
nope...
```

  updated templates/blog.html
  [ERROR] Hakyll.Core.Compiler.Require.load: templates/tag-list-new.html (snapshot _final) was not found in the cache, the cache might be corrupted or the item you are referring to might not exist
Makefile:2: recipe for target 'site' failed
make: *** [site] Error 1
```

**Comment by ranjitjhala** [comment]
Sorry what is this about again?

**Comment by atondwal** [comment]
I can't get the blog to build on my machine. This PR is for setting the image widths on the splash page in html so that if JS is off, it doesn't look horrible.

**Comment by ranjitjhala** [comment]
Are you using stack?

**Pull request closed without merging**
